baseURL = "https://kidscancode.org/godot_recipes/"
publishDir = "../docs"
languageCode = "en-us"
title = "Godot Recipes"
theme = "hugo-theme-learn-cb"
pygmentsStyle = "dracula"
pygmentsCodeFences = true
googleAnalytics = "UA-39851424-1"
disqusShortname = "kidscancode"

[params]
    disableNextPrev = true
    themeVariant = "green"
    disableInlineCopyToClipBoard = true

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
    unsafe = true

[minify]
  minifyOutput = true

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i>&nbsp;Tags"
url = "/tags"
weight = 30